### ISSUE TITLE
Deleting project.json didn't update references

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#1107]
This may only be an issue for built-in references.

Add and run this code in a manual trigger:
```
#r "Microsoft.Azure.Documents.Client"

using System;
using Microsoft.Azure.Documents;

public static void Run(string input, TraceWriter log)
{
    log.Info(typeof(Document).Assembly.Location);
}
```
You'll see the location: `D:\Program Files (x86)\SiteExtensions\Functions\1.0.10690\bin\Microsoft.Azure.Documents.Client.dll`

Add this project.json and run again:
```
{  
  "frameworks": {
      "net46": {
        "dependencies": {
          "Microsoft.Azure.DocumentDB": "1.11.1"
        }
      }
   }
}
```
You can see logs that it was installed: `D:\home\data\Functions\packages\nuget\Microsoft.Azure.DocumentDB\1.11.1\lib\net45\Microsoft.Azure.Documents.Client.dll`

Delete the project.json (and project.lock.json) and run again: `D:\home\data\Functions\packages\nuget\Microsoft.Azure.DocumentDB\1.11.1\lib\net45\Microsoft.Azure.Documents.Client.dll`

It's still referencing the old assembly.

If you restart the site, it'll go back to the original.

**Comment by fabiocav** [comment]
@brettsam have you tested this on the most recent version of the runtime? After the restart/assembly watch changes, it looks like this might have been resolved. I can't repro this with your steps using the current bits.

**Comment by brettsam** [comment]
It's entirely possible that you've fixed it already. I'll give it another shot. What about #1260?

**Comment by brettsam** [comment]
No, I still see it. I've updated the project.json above to be a higher version than we have built-in (`1.13.1`). Maybe that's the trick. I've seen a couple of people (back when I filed this) get into a state where they'd pulled in a newer version that had some breaking change, then they couldn't figure out why it still didn't work after the project.json was deleted.

**Comment by fabiocav** [comment]
I have used `1.13.1` and did see the correct behavior. Can you detail the sequence of events? Did you delete the project or the lock file first?

**Comment by fabiocav** [comment]
And I'm looking at this issue because of #1260
