### ISSUE TITLE
Timer Trigger not firing at the expected time durations

### ISSUE THREAD

**Issue by akhilaj** [Azure/azure-webjobs-sdk-script#1795]
Timer trigger are not firing at the expected time duration, we have setup a timer trigger  to run every five minutes but the function runs erratically, below is the screenshot which shows the run timings of the  timer trigger
![image](https://user-images.githubusercontent.com/5424100/29363109-43b30ad2-82ac-11e7-8a32-70a1ee774682.png)

**Comment by mathewc** [comment]
Please share your function.json details

**Comment by mathewc** [comment]
Might also be related to the other issues you're having, reported in https://github.com/Azure/azure-webjobs-sdk-script/issues/1793

**Comment by nicolocodev** [comment]
+1, my timer trigger function stops firing time to time, but, when i go to the portal and check the function (without press the `|> Run` button) starts working like a charm 😕

**Comment by akhilaj** [comment]
@mathewc Below is the function.json

{
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    }
  ],
  "disabled": false
}

**Comment by mathewc** [comment]
Guys - it turns out we did have an issue that was fixed this afternoon. You shouldn't be seeing this anymore. If you are, please reopen.

**Comment by akhilaj** [comment]
@mathewc  seems like there was a patch release which should help with this but this patch has not yet reached our function apps (SouthIndia), we are still seeing the old version, how much time it generally takes for a release to percolate across all geographies

![image](https://user-images.githubusercontent.com/5424100/29403227-5a4d9236-8355-11e7-93d9-3acc373bd42d.png)
