### ISSUE TITLE
Service Bus BrokeredMessage support for F#

### ISSUE THREAD

**Issue by JonCanning** [Azure/azure-webjobs-sdk-script#752]
Currently only works with C#, in F# I get the following error

```
mscorlib: Method not found: 'Void Microsoft.Azure.WebJobs.ServiceBusTriggerAttribute..ctor(System.String, System.String, Microsoft.ServiceBus.Messaging.AccessRights)'
```

**Comment by fabiocav** [comment]
Could you share the F# metadata and function definition?

**Comment by JonCanning** [comment]
Run.fsx
```
open System
open Microsoft.ServiceBus.Messaging

let Run(msg : BrokeredMessage, log: TraceWriter ) = log.Info("Received")
```
function.json
```
{
  "bindings": [
    {
      "name": "msg",
      "type": "serviceBusTrigger",
      "direction": "in",
      "topicName": "test",
      "subscriptionName": "test"
    }
  ]
}
```
project.json
```
{
  "frameworks": {
    "net46": {
      "dependencies": {
        "WindowsAzure.ServiceBus": "*"
      }
    }
  }
}
```

**Comment by mathewc** [comment]
There shouldn't be a language difference here at all - it's the same underlying code for all languages. Can you try removing the ServiceBus entry from your project.json? Microsoft.ServiceBus is a built in assembly - you can add it via `#r "Microsoft.ServiceBus"`. Another thing to try would be to add `accessRigghts` explicitly in your metadata as in [this](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/sample/ServiceBusTopicTrigger/function.json#L9) sample. Perhaps we have a bug there requiring this to be specified?

**Comment by JonCanning** [comment]
I've removed the project.json completely and added `#r "Microsoft.ServiceBus"` and now get this error:

`Could not resolve this reference. Could not locate the assembly "Microsoft.ServiceBus".`

**Comment by fabiocav** [comment]
Mathew's recommendation was good and should work, sot it looks like we have an issue here. We'll investigate and update this with our findings.

**Comment by dsyme** [comment]
@JonCanning @lindydonna @fabiocav @tpetricek @christopheranderson - @sylvanc and I are actively looking into this bug this week. We think nearly all the existing F# issues boil down to the one same bug (not finding assemblies at runtime which have been resolved statically)

Suspected duplicate of #650

**Comment by mathewc** [comment]
I think this should now be resolved with the recent assembly changes https://github.com/Azure/azure-webjobs-sdk-script/commit/2dd244d549adab46b5aa5752d3a6481754b81650?

**Comment by JonCanning** [comment]
I'm still seeing the error, here's the full stack trace from the logs

```
2016-11-18T20:07:45.913 Starting Host (HostId=tbrtest, Version=1.0.10604.0, ProcessId=4164, Debug=True)
2016-11-18T20:07:45.913 A ScriptHost error has occurred
2016-11-18T20:07:45.913 System.MissingMethodException: Method not found: 'Void Microsoft.Azure.WebJobs.ServiceBusTriggerAttribute..ctor(System.String, System.String, Microsoft.ServiceBus.Messaging.AccessRights)'.
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
   at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeParameterInfo target)
   at System.Reflection.RuntimeParameterInfo.GetCustomAttributesData()
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IsJobMethod>b__5(ParameterInfo p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IsJobMethod(MethodInfo method)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<GetAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken)
2016-11-18T20:07:45.913 Stopping Host
```

**Comment by fabiocav** [comment]
@JonCanning I'm assuming this is with the package reference, correct? Can you set a specific reference and point to 3.4.1?

**Comment by fabiocav** [comment]
By the way, the work that addresses this by allowing you to use a shared assembly (#r reference) has been merged but not released yet.

**Comment by JonCanning** [comment]
Still the same when setting a specific reference. Do you know when it will be released?

**Comment by fabiocav** [comment]
We hope to have it (at least in beta, which you could switch to) in about a week or so.

**Comment by JonCanning** [comment]
It's great this is fixed, but whatever changed has done this:

https://social.msdn.microsoft.com/Forums/sharepoint/en-US/db373923-129f-48d6-905a-ce1a42d54399/retrieve-the-loaderexceptions-property-for-more-information?forum=AzureFunctions

Can I set my apps to use an earlier version of the runtime until I can figure out a repro?

**Comment by fabiocav** [comment]
Yes, you can set your FUNCTIONS_EXTENSION_VERSION to ~0.9 in the meantime.

I took a closer look st this yesterday an I believe I found the issue. To test, you can disable your F# functions, particularly if you have multiple of them and they are being triggered, and try to compile and invoke one of the failing functions from the portal.

I was aldo able to repro this, so we'll have a fix out ASAP
