### ISSUE TITLE
Functions Portal proposing to downgrade from 0.7 to 0.6

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#805]
2-3 days after 0.7 release, Functions Portal still wasn't giving me the option to move forward. I decided to [switch manually with App Settings](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Function-Runtime-Versioning).

Ironically Functions Portal is now giving me option to **downgrade** from 0.7 to 0.6 😆 

> Runtime version: ~0.7. A newer version is available (~0.6).

![image](https://cloud.githubusercontent.com/assets/4225430/19642035/a1988d46-99e3-11e6-805b-221604037b4f.png)

Edit: Related to https://github.com/Azure/azure-webjobs-sdk-script/issues/798

**Comment by yvele** [comment]
Some other strange things happened.. 

1. I manually switched from 0.6 to 0.7 using App Settings
2. I updated my code (function.json, handler, etc.) to test custom routes
3. Testing my custom route was giving me a strange base64 result
4. I made this issue.. and clicked on the "downgrade" button from Function Portal.. I switched from 0.7 to 0.6
5. With 0.6 my custom route was returning nothing (like an inexisting route)
6. I switched back to 0.7 (manually) and **with no code change**, my custom route was working nicely (no more strange base64)

No enough time to investigate more.. sorry

**Comment by yvele** [comment]
PS: When Functions Portal propose me to "downgrade" from 0.7 to 0.6 a "not available.." popup appears :
![image](https://cloud.githubusercontent.com/assets/4225430/19643934/425cdbc0-99ed-11e6-850b-62d232459d83.png)

But I still can make 0.7 working with manual upgrade (0.6 to 0.7 via App Settings), [see my previous comment](https://github.com/Azure/azure-webjobs-sdk-script/issues/805#issuecomment-255704352)

**Comment by michaelz84** [comment]
@yvele: Microsoft currently does the final tests for 0.7. @mathewc explained it here:
https://github.com/Azure/azure-webjobs-sdk-script/issues/798

I assume 0.6 is still shown because the UI update will go along with the azure-webjobs-sdk-script update.

**Comment by yvele** [comment]
@michaelz84 Oops ok sorry I didn't saw #798 I think we can close this issue

**Comment by yvele** [comment]
@michaelz84 Oops ok sorry I didn't saw #798 I think we can close this issue

**Comment by michaelz84** [comment]
I would suggest opening a new issue if you can reproduce the mentioned base 64 error.

**Comment by yvele** [comment]
@michaelz84 I was thinking about that.. but unfortunately I don't have enough time to spend on investigation right now 😞

**Comment by yvele** [comment]
@mikezks The reason of the base64 : https://github.com/Azure/azure-webjobs-sdk-script/issues/814
